import { Product } from '../types'

// 30 realistic products for seeding the DropAI database
// Product data: 10 Tech Accessories, 10 Health & Wellness, 10 Home Goods
// Each product has realistic name, description, pricing, and supplier assignment

export const PRODUCTS: Array<Omit<Product, 'id' | 'created_at'>> = [
  // ─── TECH ACCESSORIES (10 products) ──────────────────────────────
  {
    name: 'Magnetic Wireless Charging Station',
    category: 'Tech Accessories',
    supplier: 'Spocket',
    cost_price: 18.50,
    selling_price: 42.99,
    profit: 24.49,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Charge your iPhone, AirPods, and Apple Watch simultaneously with this sleek 3-in-1 magnetic charging station. Features fast wireless charging, LED indicators, and a compact design that eliminates cable clutter on your desk or nightstand.',
  },
  {
    name: 'Portable Laptop Stand with Cooling Fan',
    category: 'Tech Accessories',
    supplier: 'CJDropshipping',
    cost_price: 12.00,
    selling_price: 34.99,
    profit: 22.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Ergonomic adjustable laptop stand with built-in dual cooling fans. Raises your laptop to eye level for better posture while the whisper-quiet fans prevent overheating during long work sessions. Folds flat for travel.',
  },
  {
    name: 'USB-C Hub 7-in-1 with 4K HDMI',
    category: 'Tech Accessories',
    supplier: 'AliExpress',
    cost_price: 9.50,
    selling_price: 29.99,
    profit: 20.49,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Expand your laptop connectivity instantly with 7 ports: 4K HDMI, USB-C PD charging, 2x USB-A 3.0, SD card reader, and Micro SD slot. Slim aluminum design matches premium laptops perfectly.',
  },
  {
    name: 'Premium Phone Grip + Wallet Stand',
    category: 'Tech Accessories',
    supplier: 'Spocket',
    cost_price: 3.75,
    selling_price: 14.99,
    profit: 11.24,
    stock_status: 'in_stock',
    image_url: null,
    description: 'The ultimate phone accessory — a secure grip strap, hidden card wallet, and kickstand all in one. Holds 2-3 cards safely while giving you a confident grip on your phone. Strong adhesive works with any case.',
  },
  {
    name: 'Bluetooth 5.3 Headphone Adapter',
    category: 'Tech Accessories',
    supplier: 'Zendrop',
    cost_price: 6.00,
    selling_price: 22.99,
    profit: 16.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Convert any wired headphones into wireless Bluetooth 5.3 headphones instantly. Ultra-low latency (40ms) for gaming and video. 12-hour battery life with USB-C charging. Clip-on design attaches to your collar.',
  },
  {
    name: 'Slim Power Bank 10000mAh with Built-in Cables',
    category: 'Tech Accessories',
    supplier: 'AliExpress',
    cost_price: 11.00,
    selling_price: 32.99,
    profit: 21.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Ultra-slim 10,000mAh power bank with built-in Lightning, USB-C, and Micro USB cables — no need to carry separate cords. Dual charging ports, LED battery indicator, and airline-approved safe.',
  },
  {
    name: 'Adjustable Tablet Stand for Bed',
    category: 'Tech Accessories',
    supplier: 'CJDropshipping',
    cost_price: 8.50,
    selling_price: 26.99,
    profit: 18.49,
    stock_status: 'low_stock',
    image_url: null,
    description: 'Gooseneck tablet holder that clamps to your bed frame, desk, or counter. Fully adjustable arms let you position your iPad or Kindle at any angle. Perfect for hands-free reading, watching, or cooking with recipes.',
  },
  {
    name: 'Keyboard Wrist Rest with Gel Memory Foam',
    category: 'Tech Accessories',
    supplier: 'Spocket',
    cost_price: 5.50,
    selling_price: 19.99,
    profit: 14.49,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Ergonomic gel memory foam wrist rest with non-slip bamboo base. Relieves wrist pressure during long typing sessions. Full-size design fits standard and mechanical keyboards. Easy-clean surface.',
  },
  {
    name: 'Cable Management Box with Charging Station',
    category: 'Tech Accessories',
    supplier: 'Zendrop',
    cost_price: 7.00,
    selling_price: 24.99,
    profit: 17.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Hide ugly cables and power strips inside this sleek cable management box while keeping your devices charged on top. Wood-look lid with ventilation slots. Accommodates up to 6 plugs and 3 USB devices.',
  },
  {
    name: 'Phone Lens Kit — 3 Lenses (Wide/Macro/Fisheye)',
    category: 'Tech Accessories',
    supplier: 'AliExpress',
    cost_price: 4.25,
    selling_price: 16.99,
    profit: 12.74,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Transform your phone photography with professional-grade clip-on lenses. Includes 120° wide-angle, 10x macro, and 180° fisheye lenses. Aluminum alloy body with scratch-resistant glass. Universal clip fits any phone.',
  },

  // ─── HEALTH & WELLNESS (10 products) ─────────────────────────────
  {
    name: 'Acupressure Mat with Memory Foam Pillow Set',
    category: 'Health & Wellness',
    supplier: 'Spocket',
    cost_price: 11.00,
    selling_price: 39.99,
    profit: 28.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Drug-free pain relief with 6,000+ acupressure spikes that stimulate pressure points to release tension. Includes memory foam pillow with neck support. Used by physiotherapists for back pain, neck tension, and stress relief.',
  },
  {
    name: 'Premium Blue Light Blocking Glasses',
    category: 'Health & Wellness',
    supplier: 'Zendrop',
    cost_price: 4.50,
    selling_price: 24.99,
    profit: 20.49,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Stylish anti-blue light glasses that filter 99% of harmful blue light from screens. Reduces eye strain, headaches, and improves sleep quality. Lightweight TR90 frame with scratch-resistant yellow-tinted lenses.',
  },
  {
    name: 'Infrared Heating Pad for Muscle Relief',
    category: 'Health & Wellness',
    supplier: 'CJDropshipping',
    cost_price: 14.00,
    selling_price: 44.99,
    profit: 30.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Professional-grade infrared heating pad with 3 heat settings and 4 timer options. Deep-penetrating infrared heat soothes sore muscles, cramps, and joint pain. Large 12"x24" size covers back, shoulders, or legs.',
  },
  {
    name: 'Organic Sleep Mask with Cooling Gel Layer',
    category: 'Health & Wellness',
    supplier: 'Zendrop',
    cost_price: 5.00,
    selling_price: 19.99,
    profit: 14.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Luxurious sleep mask made from organic cotton with a removable cooling gel insert. 100% blackout design with contoured eye cups that don\'t press on your lashes. Adjustable strap fits all head sizes.',
  },
  {
    name: 'Posture Corrector for Men and Women',
    category: 'Health & Wellness',
    supplier: 'Spocket',
    cost_price: 4.00,
    selling_price: 18.99,
    profit: 14.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Unobtrusive posture corrector that gently pulls your shoulders back and aligns your spine. Breathable neoprene material is comfortable under clothes. Adjustable straps for men and women. Relieves back pain from poor posture.',
  },
  {
    name: 'Fitness Resistance Bands Set (5 Levels)',
    category: 'Health & Wellness',
    supplier: 'AliExpress',
    cost_price: 3.50,
    selling_price: 15.99,
    profit: 12.49,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Complete set of 5 resistance bands from light to extra-heavy (10-50 lbs). Natural latex with reinforced seams to prevent snapping. Includes door anchor, ankle straps, carrying bag, and workout guide.',
  },
  {
    name: 'Digital Kitchen Food Scale',
    category: 'Health & Wellness',
    supplier: 'CJDropshipping',
    cost_price: 4.00,
    selling_price: 14.99,
    profit: 10.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Precision digital kitchen scale with 0.1g accuracy and 5kg capacity. Tempered glass platform with touch-sensitive controls. Tare function, auto-off, and units switch (g/oz/lb/ml). Perfect for meal prep and baking.',
  },
  {
    name: 'Foam Roller for Muscle Recovery',
    category: 'Health & Wellness',
    supplier: 'Spocket',
    cost_price: 7.00,
    selling_price: 25.99,
    profit: 18.99,
    stock_status: 'low_stock',
    image_url: null,
    description: 'High-density EVA foam roller with textured surface for deep muscle release. 18 inches long with hollow core for durability. Relieves muscle soreness, improves flexibility, and speeds up post-workout recovery.',
  },
  {
    name: 'Essential Oil Diffuser with LED Lights',
    category: 'Health & Wellness',
    supplier: 'Zendrop',
    cost_price: 6.50,
    selling_price: 22.99,
    profit: 16.49,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Ultrasonic essential oil diffuser with 200ml capacity that covers up to 300 sq ft. 7-color LED mood lighting with 2 mist modes. Auto shut-off when water runs out. Whisper-quiet operation for bedrooms and offices.',
  },
  {
    name: 'Insulated Stainless Steel Water Bottle 32oz',
    category: 'Health & Wellness',
    supplier: 'AliExpress',
    cost_price: 5.00,
    selling_price: 21.99,
    profit: 16.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Double-wall vacuum insulated water bottle that keeps drinks cold 24 hours or hot 12 hours. 32oz capacity with wide mouth for ice cubes. BPA-free stainless steel with leak-proof lid and carrying loop.',
  },

  // ─── HOME GOODS (10 products) ───────────────────────────────────
  {
    name: 'Self-Watering Smart Plant Pot',
    category: 'Home Goods',
    supplier: 'Spocket',
    cost_price: 8.00,
    selling_price: 28.99,
    profit: 20.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Self-watering planter with water level indicator that keeps plants hydrated for up to 3 weeks. Modern geometric design in matte ceramic finish. Built-in drainage system prevents root rot. Great for forgetful plant parents.',
  },
  {
    name: 'Under-Desk Foot Rest with Massage Surface',
    category: 'Home Goods',
    supplier: 'Zendrop',
    cost_price: 10.00,
    selling_price: 32.99,
    profit: 22.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Ergonomic foot rest with textured massage surface that stimulates circulation during long work hours. Adjustable height (3 positions) to find your perfect angle. Non-slip base keeps it firmly in place.',
  },
  {
    name: 'Expandable Drawer Organizer Set (8 Pack)',
    category: 'Home Goods',
    supplier: 'CJDropshipping',
    cost_price: 5.00,
    selling_price: 18.99,
    profit: 13.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Set of 8 expandable drawer dividers that adjust from 11 to 20 inches. Bamboo construction with soft-close springs. Keeps socks, underwear, office supplies, and kitchen utensils perfectly organized. No tools needed.',
  },
  {
    name: 'Slim Shoe Rack with Door Hanging Design',
    category: 'Home Goods',
    supplier: 'AliExpress',
    cost_price: 6.50,
    selling_price: 22.99,
    profit: 16.49,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Space-saving over-door shoe organizer that holds up to 12 pairs of shoes. Transparent pockets let you see your shoes at a glance. Fits standard doors without tools. Heavy-duty reinforced stitching supports boots and heels.',
  },
  {
    name: 'LED Desk Lamp with Wireless Charger',
    category: 'Home Goods',
    supplier: 'Spocket',
    cost_price: 12.00,
    selling_price: 38.99,
    profit: 26.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Smart LED desk lamp with built-in 10W wireless charging pad for your phone. 5 color temperatures and 7 brightness levels. Touch control with memory function that remembers your setting. Eye-care flicker-free technology.',
  },
  {
    name: 'Wall-Mounted Spice Rack with Magnetic Lids',
    category: 'Home Goods',
    supplier: 'Zendrop',
    cost_price: 7.50,
    selling_price: 26.99,
    profit: 19.49,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Sleek wall-mounted magnetic spice rack set with 12 glass jars and chalkboard labels. Jars stick magnetically to the steel base for easy access. Includes funnel for refilling. Saves counter space and keeps spices organized.',
  },
  {
    name: 'Collapsible Laundry Basket with Lid',
    category: 'Home Goods',
    supplier: 'CJDropshipping',
    cost_price: 5.00,
    selling_price: 16.99,
    profit: 11.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Collapsible laundry basket that folds flat to just 2 inches for easy storage. Holds 50L with ventilated sides and sturdy handles. Removable lid keeps clothes out of sight. Waterproof base protects floors.',
  },
  {
    name: 'Aromatherapy Scented Candle Set (3-Pack)',
    category: 'Home Goods',
    supplier: 'Printful',
    cost_price: 8.00,
    selling_price: 29.99,
    profit: 21.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Hand-poured soy wax candle set in 3 fragrances: Lavender Calm, Vanilla Comfort, and Eucalyptus Fresh. 40+ hour burn time each. Natural cotton wicks with no synthetic fragrances. Gift-ready packaging.',
  },
  {
    name: 'Fridge Organizer Bins (6 Pack) Clear Acrylic',
    category: 'Home Goods',
    supplier: 'AliExpress',
    cost_price: 4.00,
    selling_price: 15.99,
    profit: 11.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'Set of 6 clear acrylic fridge organizer bins in 3 sizes. Stackable design with built-in handles. Keeps cans, condiments, and produce neatly arranged. BPA-free and dishwasher safe. Fits standard refrigerator shelves.',
  },
  {
    name: 'Smart LED Strip Lights 16.4ft with App Control',
    category: 'Home Goods',
    supplier: 'CJDropshipping',
    cost_price: 6.00,
    selling_price: 24.99,
    profit: 18.99,
    stock_status: 'in_stock',
    image_url: null,
    description: 'WiFi-enabled RGB LED strip lights with app and voice control (Alexa/Google). 16.4 feet with 16 million colors and 50+ scene modes. Syncs to music with built-in microphone. Cuttable design for custom lengths.',
  },
]

export function getProductsByCategory(category: string) {
  return PRODUCTS.filter(p => p.category === category)
}

export function getProductsBySupplier(supplier: string) {
  return PRODUCTS.filter(p => p.supplier === supplier)
}

export function getMockProductData() {
  return PRODUCTS.map((p, index) => ({
    id: `prod-${String(index + 1).padStart(3, '0')}`,
    ...p,
    created_at: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString(),
  }))
}

// Supplier summary for data seeding
export const SUPPLIER_PRODUCT_COUNTS = {
  'Spocket': PRODUCTS.filter(p => p.supplier === 'Spocket').length,
  'CJDropshipping': PRODUCTS.filter(p => p.supplier === 'CJDropshipping').length,
  'AliExpress': PRODUCTS.filter(p => p.supplier === 'AliExpress').length,
  'Zendrop': PRODUCTS.filter(p => p.supplier === 'Zendrop').length,
  'Printful': PRODUCTS.filter(p => p.supplier === 'Printful').length,
}

export const CATEGORY_COUNTS = {
  'Tech Accessories': PRODUCTS.filter(p => p.category === 'Tech Accessories').length,
  'Health & Wellness': PRODUCTS.filter(p => p.category === 'Health & Wellness').length,
  'Home Goods': PRODUCTS.filter(p => p.category === 'Home Goods').length,
}
